apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: liine
resources:
  - namespace.yaml
  - configmap.yaml
  - mongo.yaml
  - minio.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: liine
    includeSelectors: false
images:
  - name: ghcr.io/codesphereit/liine
    newName: ghcr.io/codesphereit/liine
